### PR TITLE
adding name argument to _ArgvlistReader.getargvlist

### PR DESCRIPTION
**Pull request by axelfauvel**
Fixing https://github.com/jayvdb/tox-backticks/issues/16

### CODE REVIEW

**Comment by axelfauvel** [comment]
Hello @jayvdb,

I'm reached the point where all tests pass except for one : [py38-tox3_13](https://travis-ci.org/github/jayvdb/tox-backticks/jobs/756246231)

```
Traceback (most recent call last):
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/tox/config/__init__.py", line 254, in parseconfi
    pm = get_plugin_manager(plugins)
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/tox/config/__init__.py", line 73, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/pluggy/manager.py", line 289, in load_setuptools_entrypoints
    for dist in importlib_metadata.distributions():
  File "/opt/python/3.8.7/lib/python3.8/importlib/metadata.py", line 194, in <genexpr>
    resolver(context)
  File "/home/travis/build/jayvdb/tox-backticks/.tox/py38-tox3_13/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 417, in find_distributions
    found = self._search_paths(context.pattern, context.path)
AttributeError: 'Context' object has no attribute 'pattern'
```

According to [this issue on pytest](https://github.com/pytest-dev/pytest/issues/7371), python3.8 is not compatible with `importlib-metadata` < 1
If we take a look to `tox` 3.13 [setup.cfg](https://github.com/tox-dev/tox/blob/3.13.2/setup.cfg#L41) we can see that they force `importlib-metadata` < 1

We can assume that this test cannot work.

In the next commit, I will remove tox3_13 from python38 like you did with py34 and it should do the trick.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
If you could, the .py changes should be squashed into a single commit, and the tox.ini changes can be either in the same commit, or be a separate commit, and with commits that use 50cpl for the subject(first line) and 70cpl for the body.  If you do this, I'll fast forward merge, otherwise I'll use GitHub's squash and merge feature to create a single commit of them.  I'm happy either way; great to see a nice PR in my obscure little tool, and apologies I didnt notice your issue/PR until today.

**Comment by axelfauvel** [comment]
@jayvdb : i've squashed commits, please tell me if format suits you.

We're happy with your obscure litlle tool you know :)

**Comment by jayvdb** [comment]
Commits look great.  I'll fast-forward them in as soon as it is green.

**Comment by jayvdb** [comment]
Merged.  I have a few other pending changes lying around.  I'll quickly assess which of them might be ready, and do a release in a day or two.

**Pull request merged**
